# Generated by Django 5.1.4 on 2025-01-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FenixenForge_db', '0009_productdescription_titulo_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='titulo',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
