# Generated by Django 5.1.4 on 2025-01-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FenixenForge_db', '0010_alter_productdescription_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
