# Generated by Django 5.1.4 on 2025-01-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FenixenForge_db', '0011_alter_productdescription_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
