# Generated by Django 5.1.4 on 2025-01-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FenixenForge_db', '0012_remove_product_image_remove_productdescription_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='image_url',
            field=models.TextField(default=''),
        ),
    ]
